### ISSUE TITLE
possible improvements

### ISSUE THREAD

**Issue by Fantu** [veeam/blksnap#4]
I started the first fast tests, yesterday build and install deb packages on debian unstable and today build deb on ubuntu 20.04.
Unfortunately I have little time and too many things to do recently to be able to make a meaningful contribution, but at least I start with some simple and quick little things

Here a list of possible fixes/improvements spotted for now I will do:
- [x] fix instruction for create deb packages on README.md (done)
- [x] add missed deps and build-deps in deb packages (done)
- [x] decrease build-deps with only libboost parts really needed instead libboost-all-dev (done)

List of other possible improvements I suggest (if someone want do):
- add a man for usr/bin/blksnap
- unify builds of the tools, dev / library and test parts, still leaving the manual build of individual parts possible

Notes on things spotted by lintian check on generated packages:

blksnap deb package:
E: blksnap: debian-changelog-file-contains-invalid-email-address https://www.veeam.com/contacts.html

blksnap-tools deb package:
E: blksnap: debian-changelog-file-contains-invalid-email-address https://www.veeam.com/contacts.html
E: blksnap-tools: extended-description-is-empty
W: blksnap-tools: binary-without-manpage usr/bin/blksnap

blksnap-dev deb package:
E: blksnap-dev: debian-changelog-file-contains-invalid-email-address https://www.veeam.com/contacts.html
W: blksnap-dev: description-starts-with-leading-spaces

blksnap-tests deb package:
E: blksnap-tests: debian-changelog-file-contains-invalid-email-address https://www.veeam.com/contacts.html
E: blksnap-tests: depends-on-essential-package-without-using-version depends: bash
E: blksnap-tests: dir-or-file-in-opt opt/blksnap/*
E: blksnap-tests: extended-description-is-empty

As they are not packages for including in official debian and derivates repository but only minimal packages for fast testing things spotted above are not important
a small useful thing I think can be add is man for usr/bin/blksnap
another useful thing I think is generate a better version including prerelease one and git snapshot one including commit, for example 1.0.0.0~alphaN|betaN|rcN (when tagged) and when from a git snapshot include the date (date +%Y%m%d) and git commit short hash to make easy/fast for users report and developers know the exact version or commit of build. @SergeiShtepa what do you think to do about versioning?
when ready for production will be good have it also included in official distros, I'm a debian maintainer but packaging this following debian policy will require many things to do and I don't know if I'll have enough time, I maintain/help already many packages and I have too few time :(

edit:
another small question: in build.sh of deb packaging why $ARCH is taken as parameter? from a fast look I don't see crossbuild support and seems used only by Architecture field of generated package in d/control file, or I'm wrong?
if it is so can be setted directly using (`dpkg-architecture -q DEB_HOST_ARCH`)

**Comment by SergeiShtepa** [comment]
Many thanks for your attention to the project.
I think that lack of time is our common problem.
There is still a lot of work to be done in the project.
Nevertheless, in the near future I will try to devote as much time as possible to finalizing the kernel module and adding it to the upstream. After that, I will deal with the further expansion of the user-space part.
But I hope I will someday get to the completion of packages.

**Comment by Fantu** [comment]
now I did a fast build/install test on raspberry 4 with raspberry os based on debian 11 armhf and dkms failed, so I see only now in https://github.com/veeam/blksnap/blob/master/module/bdevfilter.c:289 that support only x86 actually^^'

**Comment by SergeiShtepa** [comment]
1) Yes, there is a problem with the support of different architectures. Currently, the out-of-tree version of the blksnap module can only work for amd64 and x86 architectures. The problem is in the handling mechanism, which works using live patching or directly through ftrace.
The module in the kernel should work on any architectures, theoretically. I have successfully tested the patch for the upstream on arm64el. I haven't paid enough attention to checking the module's operation on different architectures yet.

2) I tried to make a dynamic C library to work with the module. I got a very thin wrapper over system calls. Such a thin layer does not simplify the work with the module, but only creates another level of abstraction. I decided to abandon this idea.
A more complex static C++ library is too high-level an abstraction. It is good for the tests available in the project, but I think it is not suitable for backup software, except at the prototyping stage.
But maybe I'm wrong, and someone will be able to make a normal library. That is why the LGPL 2+ license is for the library code.

3) I agree with your comments. Need to do it.

**Comment by Fantu** [comment]
@SergeiShtepa Thanks for reply
I did build/install and tests run also on debian 11 amd64 vm.
I think that tests should be improved and documented (or at least a small note on readme for now), for now I did only very small and fast PR that add a log file for any tests (to make easier read full output and take them for report issue), I also did a copy of all.sh but without build/install of module that can be useful for tests of users that use deb package.
but I am not good at explaining (not even in Italian) and I am also lacking in English so I think that for the documentation it is better if someone else does it good^^'

**Comment by SergeiShtepa** [comment]
> but without build/install of module that can be useful for tests of users that use deb package.

You can take the kernel source code, apply a patch to it and build a package with this kernel, and install it.  I did it for amd64 and for my Pi 4 with arm64le (do not forget to specify the necessary kernel in the u-boot config). 

> I think that tests should be improved and documented

Creating documentation is quite a difficult task. And it's not always useful. And it is better that these are comments to the code, since in this case the access time to it is minimal.
I have tried to provide the minimum necessary documentation. He described in general terms how the module works and described how user-space interacts with the kernel module. This should be enough to start using the module. Plus some comments on the module code to facilitate the review by mantainers.
Tests were created quite spontaneously as needed, and some planned tests have not even been written yet. I think it will be a very long time before I start documenting the tests.

> better if someone else does it good

;) Every time I think like that, I have to roll up my sleeves and do everything myself.
Although there are rare exceptions.

**Comment by Fantu** [comment]
sorry for my bad english, for arm archs I don't need backup with snapshot for now, I did some tests on arm just to do some very quick miscellaneous tests and see if blksnap worked in all cases but I didn't saw arch restrinction to x86 archs for module (probably will be good add a note on doc)
about 
> I also did a copy of all.sh but without build/install of module that can be useful for tests of users that use deb package.

I mean https://github.com/veeam/blksnap/pull/7/commits/5f0e55caf6e654d13d12a116b381e84942f2c328 because using deb packages kernel module build and install can be done already in faster way in more kernel versions and devices and what is needed are only run other tests

**Comment by SergeiShtepa** [comment]
Hi.
[See](https://github.com/veeam/blksnap/pull/7#issuecomment-1200383251)

**Comment by Fantu** [comment]
@SergeiShtepa [this](https://github.com/veeam/blksnap/pull/10) done with circleci, make deb packages available for download for users/testers that want download fast/easy packages for debian 11 and 12 of any commits and PRs (as wrote in commit description add of other distros should be easy possible)

**Comment by Fantu** [comment]
@SergeiShtepa I added to circleci config also all ubuntu supported versions and I spotted that ubuntu 14.04 don't build for older cmake
```
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.5 or higher is required.  You are running version 2.8.12.2
```
and with blksnap module that support only kernel >=5.10 will not make it not working on official kernel packages (including the lts/hwe one still supported
you still want support also ubuntu 14.04 adapting build code for older cmake?
about kernel the versions supported with officiale kernel packages are only: ubuntu 20.04 (from hwe), ubuntu 22.04 and 22.10, users that will want use blksnap on older versions must use custom or unofficial build of kernel

I think is good add to readme that only kernel >=5.10 are supported

**Comment by SergeiShtepa** [comment]
Hi!
Support for old distributions is always associated with unexpected problems.
I don't think it's appropriate to do anything about it now. The blksnap module will not be able to work on kernels older than 5.10 in principle. 
Although if the user-space part of the project supports the [veeamsnap ](https://github.com/veeam/veeamsnap/) module, then it will make sense to support old distributions. I don't set myself such a task.
Therefore, I think it would be best to describe the constraints from below.

**Comment by Fantu** [comment]
Userspace part of blksnap is compatible with future blksnap upstream, blksnap module for kernel >=5.10 and if I understand your message also veemsnap older kernel module for older kernel?
I not tried veeamsnap but from a fast look seems that use internal function linked for address (https://github.com/veeam/veeamsnap/blob/master/source/genconfig.sh) that is not good (as well as other similar ones of datto and acronis)...blksnap remain the only good from a fast look
after see that using backports also with Trusty and Jessie there is required cmake version, make compatible it with older cmake version is not needed

**Comment by Fantu** [comment]
I close this and will open specific/splitted issues for the remaining ones like https://github.com/veeam/blksnap/issues/38
