### ISSUE TITLE
Unable to install on Ubuntu 22.04 LTS for KVM kernel

### ISSUE THREAD

**Issue by mikelv702** [veeam/blksnap#83]
### Distribution

Ubuntu 22.04.LTS

### Architecture

x86_64

### Kernel version

5.15.0-1049-kvm (x86_64)

### Blksnap version

6.1.0.1498

### Bug description

Unable to install through apt. 
I get the following error 
```
Error! Bad return status for module build on kernel: 5.15.0-1049-kvm (x86_64)
```

**Comment by SergeiShtepa** [comment]
Thanks, we'll take a look.

**Comment by SergeiShtepa** [comment]
> Hi, would need the module build output of dkms (like [this](https://github.com/veeam/blksnap/issues/1#issue-1200214720) or [this](https://github.com/veeam/blksnap/issues/76#issue-1986406093)) to see exactly what the error

Yes. Of course. 
No logs, no bug.

**Comment by SergeiShtepa** [comment]
My attempts to confirm this bug were unsuccessful.
I was unable to load this kernel on the KVM hypervisor available to me.
@mikelv702  or anyone else who has this problem confirmed, please send the logs.

**Comment by SergeiShtepa** [comment]
Hi!
I would like to thank my colleagues (and friends!) from the QA team.
They were able to reproduce the problem.
I am attaching the build log and the kernel configuration file.
[config-5.15.0-1050-kvm.txt](https://github.com/veeam/blksnap/files/14270005/config-5.15.0-1050-kvm.txt)
[make.log](https://github.com/veeam/blksnap/files/14270006/make.log)

The problem is: 
`# CONFIG_FUNCTION_TRACER is not set`
The module cannot handle I/O units. 

Unfortunately, I can't recommend using the veeamsnap module.
Although it is successfully installed and started, it is not able to work.
`veeamsnap:k_entries  | ERR | Failed to get address of function blk_mq_submit_bio`

I can only advise you to use generic kernel.
